/*
 * File:           TMXMapHandlerImpl.java
 * Date:           September 9, 2015  5:49 PM
 *
 * @author  cuongnguyen
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.atom.corex.world.tiled.sax;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 *
 * @author cuongnguyen
 */
public class TMXMapHandlerImpl implements TMXMapHandler {
    public static final boolean DEBUG = false;

    public void handle_terrain(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_terrain: " + meta);
        }
    }

    public void start_tileset(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_tileset: " + meta);
        }
    }

    public void end_tileset() throws SAXException {
        if (DEBUG) {
            System.err.println("end_tileset()");
        }
    }

    public void handle_ellipse(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_ellipse: " + meta);
        }
    }

    public void start_terraintypes(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_terraintypes: " + meta);
        }
    }

    public void end_terraintypes() throws SAXException {
        if (DEBUG) {
            System.err.println("end_terraintypes()");
        }
    }

    public void start_layer(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_layer: " + meta);
        }
    }

    public void end_layer() throws SAXException {
        if (DEBUG) {
            System.err.println("end_layer()");
        }
    }

    public void handle_data(final String data, final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_data: " + meta);
        }
    }

    public void handle_image(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_image: " + meta);
        }
    }

    public void handle_property(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_property: " + meta);
        }
    }

    public void start_properties(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_properties: " + meta);
        }
    }

    public void end_properties() throws SAXException {
        if (DEBUG) {
            System.err.println("end_properties()");
        }
    }

    public void start_object(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_object: " + meta);
        }
    }

    public void end_object() throws SAXException {
        if (DEBUG) {
            System.err.println("end_object()");
        }
    }

    public void handle_polygon(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_polygon: " + meta);
        }
    }

    public void handle_polyline(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_polyline: " + meta);
        }
    }

    public void start_tile(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_tile: " + meta);
        }
    }

    public void end_tile() throws SAXException {
        if (DEBUG) {
            System.err.println("end_tile()");
        }
    }

    public void start_objectgroup(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_objectgroup: " + meta);
        }
    }

    public void end_objectgroup() throws SAXException {
        if (DEBUG) {
            System.err.println("end_objectgroup()");
        }
    }

    public void start_map(final Attributes meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_map: " + meta);
        }
    }

    public void end_map() throws SAXException {
        if (DEBUG) {
            System.err.println("end_map()");
        }
    }
    
}
