/*
 * File:           TMXMapHandler.java
 * Date:           September 9, 2015  5:49 PM
 *
 * @author  cuongnguyen
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.atom.corex.world.tiled.sax;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 *
 * @author cuongnguyen
 */
public interface TMXMapHandler {

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_terrain(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_tileset(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_tileset() throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_ellipse(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_terraintypes(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_terraintypes() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_layer(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_layer() throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_data(final String data, final Attributes meta) throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_image(final Attributes meta) throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_property(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_properties(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_properties() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_object(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_object() throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_polygon(final Attributes meta) throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_polyline(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_tile(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_tile() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_objectgroup(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_objectgroup() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_map(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_map() throws SAXException;
    
}
